export enum SkillsIcons {
  React = "reactIcon",
  CSS = "cssIcon",
  NextJS = "nextJSIcon",
  TypeScript = "typeScriptIcon",
  TailwindCSS = "tailwindCSSIcon",
  PostgressSQL = "postgressSQLIcon",
  NodeJS = "nodeJSIcon",
  MongoDB = "mongoDBIcon",
  Bootstrap = "bootstrapIcon",
  ChakraUI = "chakraUIIcon",
  Firebase = "firebaseIcon",
  Github = "githubIcon",
  HTML5 = "html5Icon",
  JS = "jsIcon",
  NestJS = "nestJSIcon",
  SQL = "sqlIcon",
  Vercel = "vercelIcon",
}
